<a href="https://colab.research.google.com/github/aditi2259/CV/blob/main/CV_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x=(1,2,34)

In [4]:
type(x)

tuple

In [5]:
arr = np.array(x)

In [6]:
arr

array([ 1,  2, 34])

In [7]:
np.arange(1,20) #only low included

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
np.arange(1,11,4)

array([1, 5, 9])

In [9]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.random.seed(51)
arr1=np.random.randint(0,100,50)

In [20]:
arr1

array([57, 96, 73, 69, 16, 21, 94, 52, 37, 37, 60, 94, 28, 84, 36, 35, 27,
       28, 42, 10,  6, 25, 33, 77, 39, 48, 24, 40, 54, 77, 28, 69, 57, 18,
       63, 75, 67, 94, 87,  7, 67, 91, 61, 34, 53, 30, 55, 17, 67,  8])

In [21]:
arr1.reshape(5,10)

array([[57, 96, 73, 69, 16, 21, 94, 52, 37, 37],
       [60, 94, 28, 84, 36, 35, 27, 28, 42, 10],
       [ 6, 25, 33, 77, 39, 48, 24, 40, 54, 77],
       [28, 69, 57, 18, 63, 75, 67, 94, 87,  7],
       [67, 91, 61, 34, 53, 30, 55, 17, 67,  8]])

In [22]:
arr1.max()

96

In [23]:
arr1.min()

6

In [24]:
arr1.argmin()

20

In [25]:
arr1.mean()

49.34